import Foundation

enum PublicIDRepairManifestRecordOrigin: String, Codable, Equatable, Sendable {
    case localSwiftData
    case bridgeCollision
    case bridgeOnly
    case migratedLegacy
}

enum PublicIDRepairManifestReferenceKind: String, Codable, Equatable, Sendable {
    case foreignReference
    case ownership
    case deletionTarget
}

struct PublicIDRepairManifestRecordMapping: Identifiable, Codable, Equatable, Sendable {
    let entityType: PublicIDRepairEntityType
    let originalPublicID: UUID
    let finalPublicID: UUID
    let owningHerdPublicID: UUID?
    let portableRecordIdentity: String
    let recordFingerprint: String?
    let recordDescription: String
    let retainedOriginalID: Bool
    let origin: PublicIDRepairManifestRecordOrigin

    var id: String {
        [
            entityType.rawValue,
            originalPublicID.uuidString.lowercased(),
            portableRecordIdentity,
        ].joined(separator: "|")
    }
}

struct PublicIDRepairManifestReferenceTransformation: Identifiable, Codable, Equatable, Sendable {
    let sourceEntityType: PublicIDRepairEntityType?
    let sourcePortableRecordIdentity: String
    let fieldName: String
    let previousPublicID: UUID?
    let finalPublicID: UUID
    let owningHerdPublicID: UUID?
    let kind: PublicIDRepairManifestReferenceKind
    let origin: PublicIDRepairManifestRecordOrigin

    var id: String {
        [
            sourceEntityType?.rawValue ?? "bridge",
            sourcePortableRecordIdentity,
            fieldName,
            previousPublicID?.uuidString.lowercased() ?? "nil",
            finalPublicID.uuidString.lowercased(),
        ].joined(separator: "|")
    }

    var authorityKey: String {
        [
            sourceEntityType?.rawValue ?? "bridge",
            sourcePortableRecordIdentity,
            fieldName,
            previousPublicID?.uuidString.lowercased() ?? "nil",
            kind.rawValue,
        ].joined(separator: "|")
    }
}

struct PublicIDRepairManifestGeneration: Identifiable, Codable, Equatable, Sendable {
    let number: Int
    let capturedAt: Date
    let backup: PublicIDRepairBackupReference?
    let recordMappings: [PublicIDRepairManifestRecordMapping]
    let referenceTransformations: [PublicIDRepairManifestReferenceTransformation]
    let selectedResolutionIDs: [String]
    let bridgeRecoveryActions: [PublicIDRepairBridgeRecoveryAction]
    let validationPassed: Bool?

    var id: Int { number }
}

/// The durable authority for public-ID repair identity decisions.
///
/// Generations are monotonic snapshots. Earlier generations may be represented only by their
/// backup when decoding a legacy journal, but every identity mapping in the current generation is
/// authoritative and must be replayed rather than regenerated by local or bridge code.
struct PublicIDRepairManifest: Codable, Equatable, Sendable {
    static let currentSchemaVersion = 1

    let schemaVersion: Int
    let generations: [PublicIDRepairManifestGeneration]

    init(
        schemaVersion: Int = PublicIDRepairManifest.currentSchemaVersion,
        generations: [PublicIDRepairManifestGeneration]
    ) {
        self.schemaVersion = schemaVersion
        self.generations = generations.sorted { $0.number < $1.number }
    }

    var currentGenerationNumber: Int {
        generations.last?.number ?? 0
    }

    /// Earliest durable mapping wins. Contradictory later mappings remain in raw generations and
    /// are surfaced by `contradictions` instead of silently replacing established authority.
    var recordMappings: [PublicIDRepairManifestRecordMapping] {
        var byID: [String: PublicIDRepairManifestRecordMapping] = [:]
        for generation in generations.sorted(by: { $0.number < $1.number }) {
            for mapping in generation.recordMappings {
                if byID[mapping.id] == nil {
                    byID[mapping.id] = mapping
                }
            }
        }
        return byID.values.sorted { $0.id < $1.id }
    }

    /// Earliest durable reference decision wins. Contradictions are retained in generations and
    /// fail validation rather than being replayed.
    var referenceTransformations: [PublicIDRepairManifestReferenceTransformation] {
        var byAuthorityKey: [String: PublicIDRepairManifestReferenceTransformation] = [:]
        for generation in generations.sorted(by: { $0.number < $1.number }) {
            for transformation in generation.referenceTransformations {
                if byAuthorityKey[transformation.authorityKey] == nil {
                    byAuthorityKey[transformation.authorityKey] = transformation
                }
            }
        }
        return byAuthorityKey.values.sorted { $0.id < $1.id }
    }

    var bridgeRecoveryActions: [PublicIDRepairBridgeRecoveryAction] {
        var byID: [String: PublicIDRepairBridgeRecoveryAction] = [:]
        for generation in generations.sorted(by: { $0.number < $1.number }) {
            for action in generation.bridgeRecoveryActions {
                byID[action.id] = action
            }
        }
        return byID.values.sorted { $0.id < $1.id }
    }

    var contradictions: [String] {
        var issues: [String] = []
        let allMappings = generations.flatMap(\.recordMappings)

        let groupedMappings = Dictionary(grouping: allMappings, by: \.id)
        for (id, mappings) in groupedMappings {
            let finalIDs = Set(mappings.map(\.finalPublicID))
            let ownerIDs = Set(
                mappings.map { $0.owningHerdPublicID?.uuidString.lowercased() ?? "nil" }
            )
            if finalIDs.count > 1 || ownerIDs.count > 1 {
                issues.append(
                    "Manifest mapping \(id) has contradictory final identity or ownership."
                )
            }
        }

        // A pre-manifest pending journal can contain a local replacement that committed before a
        // bridge collision was discovered. Those legacy local replacements did not persist their
        // owning Herd. If the later bridge decision chose a different final ID, migration cannot
        // prove which physical local record the Herd-specific mapping belongs to. Keeping both as
        // independent authorities would recreate the split-brain identity bug this manifest is
        // intended to eliminate, so fail closed and require recovery from the retained backup.
        let bridgeReplacementMappings = allMappings.filter {
            $0.origin == .bridgeCollision && !$0.retainedOriginalID
        }
        let bridgeMappingsByOriginalIdentity = Dictionary(grouping: bridgeReplacementMappings) {
            [
                $0.entityType.rawValue,
                $0.originalPublicID.uuidString.lowercased(),
            ].joined(separator: "|")
        }
        for mapping in allMappings where mapping.origin == .localSwiftData
            && !mapping.retainedOriginalID
            && mapping.owningHerdPublicID == nil {
            let key = [
                mapping.entityType.rawValue,
                mapping.originalPublicID.uuidString.lowercased(),
            ].joined(separator: "|")
            guard let bridgeMappings = bridgeMappingsByOriginalIdentity[key],
                  !bridgeMappings.isEmpty else {
                continue
            }
            let bridgeFinalIDs = Set(bridgeMappings.map(\.finalPublicID))
            guard !bridgeFinalIDs.contains(mapping.finalPublicID) else { continue }
            issues.append(
                "Legacy manifest mapping \(mapping.id) has no durable Herd ownership and cannot be safely reconciled with the shared replacement mapping for the same original identity. Restore the retained pre-repair backup and rerun public-ID repair."
            )
        }

        let groupedReferences = Dictionary(
            grouping: generations.flatMap(\.referenceTransformations),
            by: \.authorityKey
        )
        for (key, transformations) in groupedReferences {
            let finalIDs = Set(transformations.map(\.finalPublicID))
            let ownerIDs = Set(
                transformations.map { $0.owningHerdPublicID?.uuidString.lowercased() ?? "nil" }
            )
            if finalIDs.count > 1 || ownerIDs.count > 1 {
                issues.append(
                    "Manifest reference \(key) has contradictory final identity or ownership."
                )
            }
        }

        return issues.sorted()
    }

    func mapping(
        entityType: PublicIDRepairEntityType,
        originalPublicID: UUID,
        owningHerdPublicID: UUID?,
        portableRecordIdentity: String? = nil
    ) -> PublicIDRepairManifestRecordMapping? {
        let candidates = recordMappings.filter {
            $0.entityType == entityType
                && $0.originalPublicID == originalPublicID
                && $0.owningHerdPublicID == owningHerdPublicID
        }
        if let portableRecordIdentity {
            return candidates.first { $0.portableRecordIdentity == portableRecordIdentity }
        }
        return candidates.count == 1 ? candidates.first : nil
    }

    func replacementPublicID(
        entityType: PublicIDRepairEntityType,
        originalPublicID: UUID,
        owningHerdPublicID: UUID
    ) -> UUID? {
        mapping(
            entityType: entityType,
            originalPublicID: originalPublicID,
            owningHerdPublicID: owningHerdPublicID
        )?.finalPublicID
    }

    static func migratingLegacy(
        completedAt: Date,
        replacements: [PublicIDRepairReplacement],
        referenceUpdates: [PublicIDRepairReferenceUpdate],
        backupFilename: String,
        backupPath: String,
        validationPassed: Bool,
        bridgeCollisionResolutions: [PublicIDRepairBridgeCollisionResolution]?,
        priorBackups: [PublicIDRepairBackupReference]?,
        bridgeRecoveryActions: [PublicIDRepairBridgeRecoveryAction]?
    ) -> PublicIDRepairManifest {
        var mappings: [PublicIDRepairManifestRecordMapping] = []
        var references: [PublicIDRepairManifestReferenceTransformation] = []

        for replacement in replacements {
            let origin: PublicIDRepairManifestRecordOrigin = replacement.stableRecordIdentifier.hasPrefix("bridge|")
                || replacement.stableRecordIdentifier.hasPrefix("bridge-")
                ? .bridgeOnly
                : .localSwiftData
            mappings.append(
                PublicIDRepairManifestRecordMapping(
                    entityType: replacement.entityType,
                    originalPublicID: replacement.retainedPublicID,
                    finalPublicID: replacement.replacementPublicID,
                    owningHerdPublicID: replacement.owningHerdPublicID,
                    portableRecordIdentity: replacement.stableRecordIdentifier,
                    recordFingerprint: replacement.recordFingerprint,
                    recordDescription: replacement.recordDescription,
                    retainedOriginalID: false,
                    origin: origin
                )
            )
            if let retainedIdentity = replacement.retainedStableRecordIdentifier {
                mappings.append(
                    PublicIDRepairManifestRecordMapping(
                        entityType: replacement.entityType,
                        originalPublicID: replacement.retainedPublicID,
                        finalPublicID: replacement.retainedPublicID,
                        owningHerdPublicID: replacement.retainedOwningHerdPublicID,
                        portableRecordIdentity: retainedIdentity,
                        recordFingerprint: replacement.retainedRecordFingerprint,
                        recordDescription: "Retained \(replacement.entityType.displayName.lowercased()) identity",
                        retainedOriginalID: true,
                        origin: .localSwiftData
                    )
                )
            }
        }

        for resolution in bridgeCollisionResolutions ?? [] {
            mappings.append(
                PublicIDRepairManifestRecordMapping(
                    entityType: resolution.entityType,
                    originalPublicID: resolution.retainedPublicID,
                    finalPublicID: resolution.retainedPublicID,
                    owningHerdPublicID: resolution.selectedHerdPublicID,
                    portableRecordIdentity: publicIDRepairManifestCrossHerdRecordIdentity(
                        entityType: resolution.entityType,
                        originalPublicID: resolution.retainedPublicID,
                        herdPublicID: resolution.selectedHerdPublicID
                    ),
                    recordFingerprint: nil,
                    recordDescription: "Retained shared \(resolution.entityType.displayName.lowercased()) identity",
                    retainedOriginalID: true,
                    origin: .bridgeCollision
                )
            )

            for replacement in resolution.authoritativeReplacementMappings {
                let portableIdentity = publicIDRepairManifestCrossHerdRecordIdentity(
                    entityType: resolution.entityType,
                    originalPublicID: resolution.retainedPublicID,
                    herdPublicID: replacement.herdPublicID
                )
                mappings.append(
                    PublicIDRepairManifestRecordMapping(
                        entityType: resolution.entityType,
                        originalPublicID: resolution.retainedPublicID,
                        finalPublicID: replacement.replacementPublicID,
                        owningHerdPublicID: replacement.herdPublicID,
                        portableRecordIdentity: portableIdentity,
                        recordFingerprint: nil,
                        recordDescription: "Shared \(resolution.entityType.displayName.lowercased()) identity",
                        retainedOriginalID: false,
                        origin: .bridgeCollision
                    )
                )
                references.append(
                    PublicIDRepairManifestReferenceTransformation(
                        sourceEntityType: nil,
                        sourcePortableRecordIdentity: "bridge-herd|\(replacement.herdPublicID.uuidString.lowercased())",
                        fieldName: "referencesTo:\(resolution.entityType.rawValue)",
                        previousPublicID: resolution.retainedPublicID,
                        finalPublicID: replacement.replacementPublicID,
                        owningHerdPublicID: replacement.herdPublicID,
                        kind: .foreignReference,
                        origin: .bridgeCollision
                    )
                )
                references.append(
                    PublicIDRepairManifestReferenceTransformation(
                        sourceEntityType: nil,
                        sourcePortableRecordIdentity: "bridge-herd|\(replacement.herdPublicID.uuidString.lowercased())",
                        fieldName: "deletionTarget:\(resolution.entityType.rawValue)",
                        previousPublicID: resolution.retainedPublicID,
                        finalPublicID: replacement.replacementPublicID,
                        owningHerdPublicID: replacement.herdPublicID,
                        kind: .deletionTarget,
                        origin: .bridgeCollision
                    )
                )
            }
        }

        for update in referenceUpdates {
            let bridgeOnly = update.stableRecordIdentifier.hasPrefix("bridge|")
                || update.stableRecordIdentifier.hasPrefix("bridge-")
            references.append(
                PublicIDRepairManifestReferenceTransformation(
                    sourceEntityType: update.entityType,
                    sourcePortableRecordIdentity: update.stableRecordIdentifier,
                    fieldName: update.fieldName,
                    previousPublicID: update.previousPublicID,
                    finalPublicID: update.repairedPublicID,
                    owningHerdPublicID: update.owningHerdPublicID,
                    kind: update.fieldName == "sharedBridgeOwner" ? .ownership : .foreignReference,
                    origin: bridgeOnly ? .bridgeOnly : .localSwiftData
                )
            )
        }

        var backupHistory = priorBackups ?? []
        let currentBackup = PublicIDRepairBackupReference(filename: backupFilename, path: backupPath)
        backupHistory.removeAll { $0.path == currentBackup.path }
        backupHistory.append(currentBackup)

        let historicalGenerations = backupHistory.dropLast().enumerated().map { offset, backup in
            PublicIDRepairManifestGeneration(
                number: offset + 1,
                capturedAt: completedAt,
                backup: backup,
                recordMappings: [],
                referenceTransformations: [],
                selectedResolutionIDs: [],
                bridgeRecoveryActions: [],
                validationPassed: nil
            )
        }
        let generationNumber = max(1, backupHistory.count)
        let explicitResolutionIDs = Set(
            (bridgeCollisionResolutions ?? []).map(\.id)
                + referenceUpdates.filter {
                    $0.stableRecordIdentifier.hasPrefix("bridge|")
                        || $0.stableRecordIdentifier.hasPrefix("bridge-")
                }.map { "\($0.stableRecordIdentifier)|\($0.fieldName)" }
                + (bridgeRecoveryActions ?? []).map(\.id)
        )
        let currentGeneration = PublicIDRepairManifestGeneration(
            number: generationNumber,
            capturedAt: completedAt,
            backup: currentBackup,
            recordMappings: deduplicatedMappings(mappings),
            referenceTransformations: deduplicatedReferenceTransformations(references),
            selectedResolutionIDs: explicitResolutionIDs.sorted(),
            bridgeRecoveryActions: bridgeRecoveryActions ?? [],
            validationPassed: validationPassed
        )
        return PublicIDRepairManifest(
            generations: historicalGenerations + [currentGeneration]
        )
    }
}

func publicIDRepairManifestCrossHerdRecordIdentity(
    entityType: PublicIDRepairEntityType,
    originalPublicID: UUID,
    herdPublicID: UUID
) -> String {
    [
        "cross-herd",
        entityType.rawValue,
        originalPublicID.uuidString.lowercased(),
        herdPublicID.uuidString.lowercased(),
    ].joined(separator: "|")
}

private func deduplicatedMappings(
    _ mappings: [PublicIDRepairManifestRecordMapping]
) -> [PublicIDRepairManifestRecordMapping] {
    var result: [PublicIDRepairManifestRecordMapping] = []
    for mapping in mappings.sorted(by: {
        if $0.id == $1.id {
            return $0.finalPublicID.uuidString < $1.finalPublicID.uuidString
        }
        return $0.id < $1.id
    }) where !result.contains(mapping) {
        result.append(mapping)
    }
    return result
}

private func deduplicatedReferenceTransformations(
    _ transformations: [PublicIDRepairManifestReferenceTransformation]
) -> [PublicIDRepairManifestReferenceTransformation] {
    var result: [PublicIDRepairManifestReferenceTransformation] = []
    for transformation in transformations.sorted(by: {
        if $0.authorityKey == $1.authorityKey {
            return $0.finalPublicID.uuidString < $1.finalPublicID.uuidString
        }
        return $0.authorityKey < $1.authorityKey
    }) where !result.contains(transformation) {
        result.append(transformation)
    }
    return result
}
